### ISSUE TITLE
test is failing in travis

### ISSUE THREAD

**Issue by pravi** [micromatch/extglob#11]
please fix https://travis-ci.org/micromatch/extglob/jobs/319978827

**Comment by jonschlinkert** [comment]
[as it says in the code](https://github.com/micromatch/extglob/blob/master/test/test.js#L17), this fails in bash. It's a failing test, that (for now) is going to continue to fail and should be skipped. I just forgot to re-skip the test before pushing it up.

**Comment by jonschlinkert** [comment]
published and released as 2.0.4
